# https://packit.dev/docs/configuration/

specfile_path: koji-image-builder.spec
downstream_package_name: koji-image-builder

files_to_sync:
  - koji-image-builder.spec
  - .packit.yaml

copy_upstream_release_description: true

upstream_tag_template: v{version}

# Handle only releases without a "dot" (e.g. v88.2), since "dot" releases should never be released to Fedora
upstream_tag_include: 'v\d+'

jobs:
  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-branched  # rawhide updates are created automatically
      - epel-10
      - epel-9
  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all
      - epel-10
      - epel-9
  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-all
      - epel-10
      - epel-9
  - job: copr_build
    trigger: pull_request
    targets: &build_targets
      - fedora-all-aarch64
      - fedora-all-s390x
      - fedora-all-ppc64le
      - fedora-all
      - epel-9-aarch64
      - epel-9-s390x
      - epel-9-ppc64le
      - epel-9-x86_64
      - epel-10-aarch64
      - epel-10-s3100x
      - epel-10-ppc64le
      - epel-10-x86_64
  - job: copr_build
    trigger: commit
    branch: main
    owner: "@osbuild"
    project: image-builder
    targets: *build_targets
