# https://packit.dev/docs/configuration/

specfile_path: koji-image-builder.spec
downstream_package_name: koji-image-builder

files_to_sync:
  - koji-image-builder.spec
  - .packit.yaml

copy_upstream_release_description: true

upstream_tag_template: v{version}

# Handle only releases without a "dot" (e.g. v88.2), since "dot" releases should never be released to Fedora
upstream_tag_include: 'v\d+'

jobs:
  - job: copr_build
    trigger: pull_request
    targets: &build_targets
      - fedora-all-aarch64
      - fedora-all-s390x
      - fedora-all-ppc64le
      - fedora-all
  - job: copr_build
    trigger: commit
    branch: main
    owner: "@osbuild"
    project: image-builder
    targets: *build_targets
